#!/bin/bash

echo "DA USARE CON SOURCE"
echo "ricorda di fare: ml gcc/11.3.0 openmpi/4.1.4--gcc--11.3.0-cuda-11.8"

# activate spack
. $WORK/space_stuff/spack/share/spack/setup-env.sh

# activate the scorep enviroiment
spack env activate -d $WORK/space_stuff/spack_env_scorep/

# load scorep and scalasca
spack load scorep
spack load scalasca
