#!/bin/bash

module purge

module load cuda/11.8 
module load openmpi/4.1.4--gcc--11.3.0-cuda-11.8
module load cmake/3.24.3
module load hdf5/1.12.2--gcc--11.3.0

echo " *** Remember to set the default compute capability to 80 in the CMakelists for ISTEDDAS to run on the A100 ***"

module list

